import type { Metadata } from 'next'
import { Albert_Sans } from 'next/font/google'
import Image from 'next/image'
import Link from 'next/link'
import './globals.css'

const albert = Albert_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={albert.className}>
        <header>
          <Link href='/' className='flex items-center gap-2 px-4 py-2'>
            <Image src='/tailwind_icon.svg' alt='logo' width={38} height={38} />
            <h1 className='text-[24px] font-semibold'>Tailwind UI 연습</h1>
          </Link>
        </header>
        {children}
      </body>
    </html>
  )
}
